/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_java.UI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import projet_java.model.Catalogue;
import projet_java.model.Utilisateur;
import projet_java.service.GestionUtilisateurs;

/**
 *
 * @author nabil
 */
public class FenetreInscription extends javax.swing.JFrame {

    //final pour que l'objet utilisé soit le meme, ça m'évitera de le réinitialiser 
    //par erreur et de perdre les données que j'aurai chargé
    private final GestionUtilisateurs gestionUsers;
    private final Catalogue catalogue;

    /**
     * Creates new form FenetreInscription
     */
    public FenetreInscription(GestionUtilisateurs gu, Catalogue cat) {
        initComponents();
        //l'attribut gestionUser de l'objet reçoit l'objet gestionU
        this.gestionUsers = gu;
        //idem ici pour le catalogue
        this.catalogue = cat;

        //on fait les réglages pour le titre de la page de connexion
        setTitle("Inscription");
        setSize(520, 360);
        setLocation(200, 200);

        //si on ferme cette fentre, l'appli se ferme
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCreer = new javax.swing.JButton();
        btnRetour = new javax.swing.JButton();
        tfPass2 = new javax.swing.JPasswordField();
        tfPass1 = new javax.swing.JPasswordField();
        tfLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login");

        jLabel2.setText("Mot de passe");

        jLabel3.setText("Confirmer mot de passe");

        btnCreer.setText("Créer");
        btnCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreerActionPerformed(evt);
            }
        });

        btnRetour.setText("Retour");
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });

        tfPass2.setColumns(15);

        tfPass1.setColumns(15);

        tfLogin.setColumns(15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreer)
                            .addComponent(btnRetour))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnCreer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRetour)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreerActionPerformed
        // TODO add your handling code here:

        //on créé 3 string, l'un pour le login, un pour le mot de passe et le dernier pour la confirmation du mot de passe
        String login = tfLogin.getText();//on récupère le texte saisi par l'utilisateur dans tfLogin, c'est un textfield

        //getPassword renvoie un tableau de char, pas un string
        //donc pour manipuler un string, je dois convertir en string
        //je créé donc un objet string, que j'appelle mdp pour mot de passe et qui 
        //va recevoir le contenu du tableau de char et en fera un string
        String mdp1 = new String(tfPass1.getPassword());
        String mdp2 = new String(tfPass2.getPassword());

        //on gère 3 cas que nos conditions if vont attraper et stoper la méthode si on rentre dans le if, enfin dans l'un d'eux
        //on contrôles le champ de texte de login, donc si l'utilisateur a saisi qq chose
        if (login == null || login.length() == 0) {
            //s'il s'avère que le champ est vide, l'utilisateur n'a rien rempli, on en informe alors l'utilisateur

            JOptionPane.showMessageDialog(this, "Le login ne peut pas être vide.");

            //le return sort de la méthode, ce qui va permettre de ne pas l'exécuter et de pas 
            //continuer vers la connexion ou l'inscription, la page restera telle quelle
            return;
        }

        //un autre cas est si le champ pour le mot de passe est vide, il se passe laors la meme chose
        if (mdp1 == null || mdp1.length() == 0) {
            JOptionPane.showMessageDialog(this, "Le mot de passe ne peut pas être vide.");
            return;
        }
        if (mdp1.equals(mdp2) == false) {
            JOptionPane.showMessageDialog(this, "Les deux mots de passe ne correspondent pas.");
            return;
        }

        //on a controle que le login et le mot de passe sont bons, on peut donc tenter l'inscription si nos deux if n'ont pas attrape d'anomalie
        //on appelle alors la méthode qui permet de faire l'inscription, la méthode renvoie un objet utilisateur si tt est ok 
        Utilisateur u = gestionUsers.inscrire(login, mdp1);

        //si aucun utilisateur n'est renvoyé par la méthode, on affiche un message d'échec d'inscription et on arrete la procédure
        if (u == null) {
            JOptionPane.showMessageDialog(this, "Échec de l'inscription : login déjà pris ou données invalides.");
            return;
        }

        //ensuite, on doit sauvegarder les modifis de la liste des utilisateurs en réécrivant dans le fichier txt
        //donc on appelle la fonction de sauvegarde dans le fichier de la classe gestionUtilisateur en appelant le fichier txt
        gestionUsers.sauvegarderDansFichier("data/utilisateurs.txt");

        //si on n'est pas entré dans les if qui renvoient un return et terminent la méthode, 
        //alors on considère que le compte a bein été créé, on affiche donc un message qui en informe l'utilisateur
        JOptionPane.showMessageDialog(this, "Compte créé avec succès ! Vous pouvez vous connecter.");

        //la création du compte ayant marché, on renvoie sur la page de connexion, 
        //il suffira alors à l'utilisateur de saisir son login et mot de passe du compte qu'il vient de créer pour se connecter
        FenetreConnexion fc = new FenetreConnexion(gestionUsers, catalogue);
        this.setVisible(false);//on cache la fentre actuelle 
        fc.setVisible(true); //on rend visible la fenetre de connexion

    }//GEN-LAST:event_btnCreerActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
        // TODO add your handling code here:

        // retour à la fenêtre de connexion si l'utilisateur clique sur le bouton de retour
        //on créé un objet fenetre de connexion et on la rend visible tout en cachant la fentre d'inscription
        FenetreConnexion fc = new FenetreConnexion(gestionUsers, catalogue);
        this.setVisible(false);
        fc.setVisible(true);
    }//GEN-LAST:event_btnRetourActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreer;
    private javax.swing.JButton btnRetour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JPasswordField tfPass1;
    private javax.swing.JPasswordField tfPass2;
    // End of variables declaration//GEN-END:variables
}
