/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_java.UI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import projet_java.model.Catalogue;
import projet_java.model.Utilisateur;

import projet_java.service.GestionUtilisateurs;

/**
 *
 * @author nabil
 */
public class FenetreConnexion extends javax.swing.JFrame {

    //final pour que l'objet utilisé soit le meme, ça m'évitera de le réinitialiser 
    //par erreur et de perdre les données que j'aurai chargé
    private final GestionUtilisateurs gestionUsers;
    private final Catalogue catalogue;

    /**
     * Creates new form FenetreConnexion
     */
    //on passe en argumetn le catalogue de manga et la gestion des utilisateurs
    public FenetreConnexion(GestionUtilisateurs gu, Catalogue cat) {
        initComponents();

        //l'attribut gestionUser de l'objet reçoit l'objet gestionU
        this.gestionUsers = gu;
        //idem ici pour le catalogue
        this.catalogue = cat;

        //on fait les réglages pour le titre de la page de connexion
        setTitle("Connexion");
        setSize(520, 320);
        setLocation(240, 180);

        //si on ferme cette fentre, l'appli se ferme
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JLabel();
        MotDePasse = new javax.swing.JLabel();
        btnConnexion = new javax.swing.JButton();
        btnInscription = new javax.swing.JButton();
        tfLogin = new javax.swing.JTextField();
        tfPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Login.setText("Login");

        MotDePasse.setText("Mot de passe");

        btnConnexion.setText("Connexion");
        btnConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnexionActionPerformed(evt);
            }
        });

        btnInscription.setText("Créer un compte");
        btnInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriptionActionPerformed(evt);
            }
        });

        tfLogin.setColumns(15);
        tfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoginActionPerformed(evt);
            }
        });

        tfPass.setColumns(15);
        tfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MotDePasse))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(Login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MotDePasse)
                .addGap(5, 5, 5)
                .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConnexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInscription)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriptionActionPerformed
        // TODO add your handling code here:

        //au final, ici on va juste rediriger vers l apage d'inscipttion
        // Ouvrir la fenêtre d’inscription
        //on créé un nouvel objet fentre d'inscription et elle prend ne argument le catalgoue des mangas et la gestion des utilisateurs
        FenetreInscription fi = new FenetreInscription(gestionUsers, catalogue);
        fi.setTitle("Inscription");
        fi.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fi.setSize(520, 360);
        fi.setLocation(260, 200);

        // Masquer la fenêtre de connexion pendant l’inscription
        this.setVisible(false);
        fi.setVisible(true);

        /* JE PASSE TOUT CE BLOC EN COMMENTAIRE CAR IL NE DOIT PAZS ETRE LA MAIS DANS FENTRE INSCRIPTION EN VRAI
        //on créé 2 strings, un login et un mot de passe
        String login = tfLogin.getText();//on récupère le texte saisi par l'utilisateur dans tfLogin, c'est un textfield

        //getPassword renvoie un tableau de char, pas un string
        //donc pour manipuler un string, je dois convertir en string
        //je créé donc un objet string, que j'appelle mdp pour mot de passe et qui 
        //va recevoir le contenu du tableau de char et en fera un string
        String mdp = new String(tfPass.getPassword());//on construit un objet string et cet objet va contenir le mot de passe

        //on contrôles le champ de texte de login, donc si l'utilisateur a saisi qq chose
        if (login == null || login.length() == 0) {
            //s'il s'avère que le champ est vide, l'utilisateur n'a rien rempli, on en informe alors l'utilisateur
            JOptionPane.showMessageDialog(this, "Le login ne peut pas être vide.");
            //le return sort de la méthode, ce qui va permettre de ne pas l'exécuter et de pas 
            //continuer vers la connexion ou l'inscription, la page restera telle quelle
            return;
        }
        //on controle le champ de texte de mot de passe, c'est le meme fonctionnement que pour login
        if (mdp == null || mdp.length() == 0) {
            JOptionPane.showMessageDialog(this, "Le mot de passe ne peut pas être vide.");
            return;
        }

        //on appelle la méthode pour inscrire un utilisateur, elle vient de gestion utilisateur 
        //ça renverra null si ça échoue, et ça créé un objet utilisateur si ça réussi
        //la méthode prend en argument le login et le mot de passe saisis pur créer un utilisateur
        Utilisateur u = gestionUsers.inscrire(login, mdp);

        //test pour voir si l'inscription est passée ou pas
        //si u est null, c'est que la création de l'utilisateur n'a pas marché
        //ce test vérifie si la création de l'utilisateur est passée, pas les chanps de texte individuellement
        if (u == null) {
            //si on rentre dans ce if, l'inscription n'est pas passée donc on affiche ce message
            JOptionPane.showMessageDialog(this, "Échec de l'inscription : login déjà pris ou données invalides.");
            return; // on n'enchaîne pas, comme pour les if dessus, on reste sur la meme page
        }

        
        /* le bloc ci-dessous doit etre dans la fentre d'inscription seulement, pas ici !
        
        //ensuite, on doit sauvegarder les modifis de la liste des utilisateurs en réécrivant dans le fichier txt
        //donc on appelle la fonction de sauvegarde dans le fichier de la classe gestionUtilisateur en appelant le fichier txt
        gestionUsers.sauvegarderDansFichier("data/utilisateurs.txt");

        //si on n'est pas entré dans les if qui renvoient un return et terminent la méthode, 
        //alors on considère que le compte a bein été créé, on affiche donc un message qui en informe l'utilisateur
        JOptionPane.showMessageDialog(this, "Compte créé avec succès ! Vous pouvez vous connecter.");
         */
 /*       
        
        //la création du compte ayant marché, on renvoie sur la page de connexion, 
        //il suffira alors à l'utilisateur de saisir son login et mot de passe du compte qu'il vient de créer pour se connecter
        FenetreConnexion fc = new FenetreConnexion(gestionUsers, catalogue);

        //enfin, on fait les réglages de la fentre qui s'affiche
        fc.setTitle("Connexion");
        fc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fc.setSize(520, 320);
        fc.setLocation(240, 180);

        //on cache la fenetre d'inscription car c'est deja fait et on affiche la fenetre de connexion
        this.setVisible(false);
        fc.setVisible(true);
         */
    }//GEN-LAST:event_btnInscriptionActionPerformed

    private void btnConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnexionActionPerformed
        // TODO add your handling code here:

        //on créé 2 variables string qui vont récupérer les saisies des champs pour le login et l emot de passe
        String login = tfLogin.getText();                 // ici c'est un string donc c'est bon
        String mdp = new String(tfPass.getPassword());  // là, comme plus haut dans le code, c'est un tableau de char, on doit le convertir en string

//ici c'est exactement comme le bouton d'inscription pour ces deux if, donc je les reprend tel quel        
//on contrôles le champ de texte de login, donc si l'utilisateur a saisi qq chose
        if (login == null || login.length() == 0) {
            //s'il s'avère que le champ est vide, l'utilisateur n'a rien rempli, on en informe alors l'utilisateur
            JOptionPane.showMessageDialog(this, "Le login ne peut pas être vide.");
            //le return sort de la méthode, ce qui va permettre de ne pas l'exécuter et de pas 
            //continuer vers la connexion ou l'inscription, la page restera telle quelle
            return;
        }
        //on controle le champ de texte de mot de passe, c'est le meme fonctionnement que pour login
        if (mdp == null || mdp.length() == 0) {
            JOptionPane.showMessageDialog(this, "Le mot de passe ne peut pas être vide.");
            return;
        }

        //on a controle que le login et le mot de passe sont bons, on peut donc tenter la connexion si nos deux if n'ont pas attrape d'anomalie
        //on appelle alors la méthode qui permet de faire la connexion, la méthode renvoie un objet utilisateur si tt est ok 
        Utilisateur u = gestionUsers.connecter(login, mdp);

        //on doit gérer plusieurs cas : si jamais les identifants posent problème, si ça correspond 
        //à un compte admin et enfin si c'est un compte visiteur
        //si jamais les indietifiants, donc le login ou le mot de passe, sont incorrects
        //la méthode juste au-dessus, donc connecter, renvoi null si aucun utilisateur trouvé
        if (u == null) {
            //on affiche alors  ce message pour dire à lutilisateur que ses idnetifiants sont pas bons
            JOptionPane.showMessageDialog(this, "Identifiants invalides.");
            return; // on arrete la méthode là
        }

        //il reste deux cas à gérer : admin ou visiteur ?
        //si l'objet utilisateur eetourné par la méthode a un attribut rle qui correspond à admin, 
        //alors c'est un admin et on affiche donc l'écran des admins, qui donnera accès à ses propres fonctionnalités
        if (u.estAdmin()) {
            //si c'est un admin, on ouvre la fentre d'administration
            FenetreAdminMenu fa = new FenetreAdminMenu(gestionUsers, catalogue, u, this);
            fa.setTitle("Administration");
            fa.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            fa.setSize(860, 580);
            fa.setLocation(140, 110);

            //on masque la fenêtre de connexion et on affiche l'admin
            this.setVisible(false);
            fa.setVisible(true);
        } //sinon, c'est pas un admin mais les login et mot de passe sont valide,s c'est donc un visiteur normal, 
        //il arrivera alors sur la page d'accueil du site, permettant d'accéder à la reco, 
        //de consulter ses favoris et de se déconnecter
        else {
            //sinon, c'est un utilisateur normal, on ouvre l'accueil
            FenetreAccueil f = new FenetreAccueil(gestionUsers, catalogue, u);
            f.setTitle("Accueil");
            f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            f.setSize(720, 480);
            f.setLocation(220, 160);

            this.setVisible(false);
            f.setVisible(true);
        }

    }//GEN-LAST:event_btnConnexionActionPerformed

    private void tfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassActionPerformed

    private void tfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    //je passe tout ce bloc en commentaire car j'ai deja un main dans projet java app

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JLabel MotDePasse;
    private javax.swing.JButton btnConnexion;
    private javax.swing.JButton btnInscription;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JPasswordField tfPass;
    // End of variables declaration//GEN-END:variables

}
