/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_java.UI;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import projet_java.model.Catalogue;
import projet_java.model.Utilisateur;
import projet_java.service.GestionUtilisateurs;

/**
 *
 * @author nabil
 */
public class FenetreAdminUtilisateurs extends javax.swing.JFrame {

    //final permet d'^tre sur que quand on arrive dans cet ecran, le catalogue ou l'utilisateur ne changeront pas
    //le private permet que les infos de l'utilisateur connecté ne changent pas, donc l'utilisateur connecté ne changera pas avant déconnexion par exempke
    private final GestionUtilisateurs gestionUsers; //c'est lo'bjet qui gère les utilisateurs
    private final Catalogue catalogue; //le catalogue des mangas
    private final Utilisateur adminCourant;  // c'est l'utilisateur qui est connecté, ici un admin, on s'en servira poiur qu'il ne puisse pas se supprimer lui-m
    private final JFrame ecranRetour;

    //on créé un model de liste pour la liste des utilisateurs,n l'appliquera a notre jliste     
    private final DefaultListModel<String> modelUsers = new DefaultListModel<>();

    /**
     * Creates new form FenetreAdminUtilisateurs
     */
    public FenetreAdminUtilisateurs(GestionUtilisateurs gu, Catalogue cat, Utilisateur u, JFrame retour) {
        initComponents();

        //on affecte les attrubts de l'objet fenetre d'accueil 
        this.gestionUsers = gu;
        this.catalogue = cat;
        this.adminCourant = u;

        //on mémorise la fenetre juste avant, celle qui a ouvert la fiche manga, pour pouvoir revenir ne arrière
        this.ecranRetour = retour;

        //on fait les regalges de la fenetre
        // au final le settitel est inutile vu que je mets deja le titre en design sur netbeans setTitle("Gestion des utilisateurs");
        setSize(560, 380);
        setLocation(300, 200);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        //on lie notre model à notre jliste et on y charge la liste des utilisateurs
        listeAdminUtilisateur.setModel(modelUsers);
        rafraichirListeUsers();

    }
    //on fait la méthode qui va permettre de charger la liste avec les infos des utilisateurs
/*
    private void rafraichirListeUsers() {
        //on commence par vider la liste
        modelUsers.removeAllElements();
        if (gestionUsers != null) {
            //si l'objet gestion user est non null, on cvréé une liste en appelant la methode permettant d'obtenir les utilisateurs
            ArrayList<Utilisateur> listeUtilisateurs = gestionUsers.getUtilisateurs(); 
            //si la liste obtenue est non nulle, on la parcourt avec un for each

            /* V1, c'est inutile en vrai le if listeuser != null
            if (listeUtilisateurs != null) {
                for (Utilisateur u : listeUtilisateurs) {
                    //si l'utilisateur en cours n'est pas null et qu'on accède à son login
                    if (u != null && u.getLogin() != null) {
                        //on ajoute le login de l'utilisateur à la liste
                        modelUsers.addElement(u.getLogin());
                    }
                }
            }
     */

    private void rafraichirListeUsers() {
        //on vide la liste
        modelUsers.removeAllElements();
        //on parcourt la liste qui est récupérée via la methode getutilisateur
        for (Utilisateur u : gestionUsers.getUtilisateurs()) {
            //si un utilisateur est trouvé et que son login est trouvé
            if (u != null && u.getLogin() != null) {
                //alors on l'ajoute à la liste
                modelUsers.addElement(u.getLogin());
            }
        }
    }

    //on créé aussi une methode pour trouver un uitilisateur par login
    //on se base sur la methode qui existe deja dazns la classe gestion  utilisateurs 
    private Utilisateur chercherParLogin(String login) {
        //si gestion user ne renvoie rien, on arrete la methode, ça ne devrait pas arriver vu que je kl'ai initialisé au constructuer en haut mais je laisse au cas ou
        if (gestionUsers == null) {
            return null;
        }
        //sinon on renvoie l'utilisateur identifié par un login donné
        return gestionUsers.rechercherParLogin(login);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreAdminUtilisateur = new javax.swing.JLabel();
        btnDeconnexionAdminUtilisateur = new javax.swing.JButton();
        btnRetourAdminUtilisateur = new javax.swing.JButton();
        btnAjouterAdminUtilisateur = new javax.swing.JButton();
        btnModifierAdminUtilisateur = new javax.swing.JButton();
        btnSupprimerAdminUtilisateur = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeAdminUtilisateur = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titreAdminUtilisateur.setText("Aministration des utilisateurs");

        btnDeconnexionAdminUtilisateur.setText("Déconnexion");
        btnDeconnexionAdminUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeconnexionAdminUtilisateurActionPerformed(evt);
            }
        });

        btnRetourAdminUtilisateur.setText("Retour");
        btnRetourAdminUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourAdminUtilisateurActionPerformed(evt);
            }
        });

        btnAjouterAdminUtilisateur.setText("Ajouter");
        btnAjouterAdminUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterAdminUtilisateurActionPerformed(evt);
            }
        });

        btnModifierAdminUtilisateur.setText("Modifier");
        btnModifierAdminUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierAdminUtilisateurActionPerformed(evt);
            }
        });

        btnSupprimerAdminUtilisateur.setText("Supprimer");
        btnSupprimerAdminUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerAdminUtilisateurActionPerformed(evt);
            }
        });

        listeAdminUtilisateur.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeAdminUtilisateur.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listeAdminUtilisateur);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 116, Short.MAX_VALUE)
                        .addComponent(titreAdminUtilisateur)
                        .addGap(46, 46, 46)
                        .addComponent(btnDeconnexionAdminUtilisateur))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSupprimerAdminUtilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAjouterAdminUtilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModifierAdminUtilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRetourAdminUtilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titreAdminUtilisateur)
                    .addComponent(btnDeconnexionAdminUtilisateur))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnAjouterAdminUtilisateur)
                        .addGap(20, 20, 20)
                        .addComponent(btnModifierAdminUtilisateur)
                        .addGap(18, 18, 18)
                        .addComponent(btnSupprimerAdminUtilisateur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(btnRetourAdminUtilisateur)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetourAdminUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourAdminUtilisateurActionPerformed
        // TODO add your handling code here:

        //on revient à la fenêtre qui a ouvert le menu
        if (ecranRetour != null) {
            this.setVisible(false);//on cache la fenetre actuelle
            ecranRetour.setVisible(true);  //on affiche la fenetre d'avant
        } else {
            // normalement on entrera pas dans ce if mais si jamais j'ai raté un bout de code, en failsafe ça revient à l'accueil
            FenetreAccueil fa = new FenetreAccueil(gestionUsers, catalogue, adminCourant);
            this.setVisible(false);
            fa.setVisible(true);
        }
    }//GEN-LAST:event_btnRetourAdminUtilisateurActionPerformed

    private void btnAjouterAdminUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterAdminUtilisateurActionPerformed
        // TODO add your handling code here:

        //on créé un login qui va récupérer la saisie de l'admin qui va créer le compte
        String login = JOptionPane.showInputDialog(this, "Login :");
        //si aucun login n'est saisi, rien ne se passe
        if (login == null || login.length() == 0) {
            return;
        }
        //une fois le login saisi, on vérifie s'il n'existe pas deja
        if (chercherParLogin(login) != null) {
            //on affiche alors un message disant que le login est deja pris et rien ne se passe
            JOptionPane.showMessageDialog(this, "Ce login existe déjà.");
            return;
        }

        //on créé le mot de passe pour l'utilisateur
        //le fonctionnement du bloc ci-dessous est pareil que pour le login sauf qu'on ne vérifie pas que le mot de passe est deja pris, pas utile
        String mdp = JOptionPane.showInputDialog(this, "Mot de passe :");
        if (mdp == null || mdp.length() == 0) {
            return;
        }

        //idem, cette fois on fait choisir le role
        int rep = JOptionPane.showConfirmDialog(
                this,
                "Cet utilisateur doit-il être ADMIN ?",
                "Rôle",
                JOptionPane.YES_NO_OPTION
        );

        //on créé un booléen vérifiant si l'utilisateur est admin ou pas, à false par defaut 
        boolean estAdmin = false;
        //si l'admin choisi que le compte créé doit etre admin, alors le booléen passera à true
        if (rep == JOptionPane.YES_OPTION) {
            estAdmin = true;
        }

        //on créé alors le compte avec gestion user
        //la methode qu'on appelle depuis gestion user prend en paramètre le llogin et le mot de passe qu'on a saisi
        Utilisateur nouveau = gestionUsers.inscrire(login, mdp);
        //en cas d'echec de la création, je laisse cette protection
        if (nouveau == null) {
            //en cas d'échec on prévient l'admin que ça a echoué
            JOptionPane.showMessageDialog(this, "Échec de la création (login déjà pris ou données invalides).");
            return;
        }

        //si jamais l'admin a choisi que le comtpe devait etre admin, on promeut le compte
        if (estAdmin) {
            //on appelle al methode qui sert à passer en admin un compte
            //ça prend ne paramètre le nouveau compte créé
            gestionUsers.promouvoir(nouveau);
        }

        //plus qu'à sauvegarder la création du compte
        gestionUsers.sauvegarderDansFichier("data/utilisateurs.txt");

        //enfin, on remet à jour la liste avec le nouvel utilisateur
        rafraichirListeUsers();

        //on ajoute un message pour confirmer que ça a bien été fait
        JOptionPane.showMessageDialog(this, "Utilisateur ajouté : " + login);

    }//GEN-LAST:event_btnAjouterAdminUtilisateurActionPerformed

    private void btnModifierAdminUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierAdminUtilisateurActionPerformed
        // TODO add your handling code here:

        //on créé un index qui va récupéréer li'ndice de l'élément sélectionné dans la liste
        int index = listeAdminUtilisateur.getSelectedIndex();
        //par défaut, la valeur est à -1, si on sélectionne un élément, la valeur sera nécéssairement différente de -1
        if (index == -1) {
            //on affiche un message prévenant de l'erreur
            JOptionPane.showMessageDialog(this, "Sélectionne un utilisateur.");
            return;
        }

        //on créé un string qui va récupérer l'élélemnt de la liste à l'indice sélectionné
        String login = modelUsers.getElementAt(index);

        // u se voit affecté l'utilisateur trouvé par le login
        Utilisateur u = chercherParLogin(login);

        //si aucun utilisateur n'est trouvé, on affiche ce message et on arrete la méthode
        if (u == null) {
            JOptionPane.showMessageDialog(this, "Utilisateur introuvable.");
            return;
        }

        //on créé un int qui va récupérer la réponse de l'utilisateru
        int rep = JOptionPane.showConfirmDialog(
                this,
                "Basculer le rôle ?\n(Oui = ADMIN, Non = VISITEUR, Annuler = inchangé)",
                "Rôle",
                JOptionPane.YES_NO_CANCEL_OPTION
        );

        //test, si l'utilisateur choisi cancel, l'action est annulée, rien ne se passe
        if (rep == JOptionPane.CANCEL_OPTION) {
            return;
        } //sinon, si l'utilisateur choisi oui, on promeut l'utilisateur
        else if (rep == JOptionPane.YES_OPTION) {
            gestionUsers.promouvoir(u);
        } //sinon, on retrograde l'utilisateur par défaut, meme s'il était visiteur, on le repasse visitreur, ça changera rien pour lui
        else if (rep == JOptionPane.NO_OPTION) {
            gestionUsers.retrograder(u);
        }

        //on sauvegarde la modification de l'utilisateur dans le fichier txt
        gestionUsers.sauvegarderDansFichier("data/utilisateurs.txt");

        //on remet à jour la liste après la mise à jour
        rafraichirListeUsers();
        JOptionPane.showMessageDialog(this, "Modification effectuée.");
    }//GEN-LAST:event_btnModifierAdminUtilisateurActionPerformed

    private void btnSupprimerAdminUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerAdminUtilisateurActionPerformed
        // TODO add your handling code here:

        //on créé un indice, il récupère l'indice du manga sélectionné
        int index = listeAdminUtilisateur.getSelectedIndex();

        //si l'indice vaut -1, alors c'est par défaut car aucun manga n'est sélectionné
        if (index == -1) {
            //on affiche alors un message et on arrete la méthode
            JOptionPane.showMessageDialog(this, "Sélectionne un utilisateur.");
            return;
        }

        //on créé un string pour régupérer le login de l'utilisateur de l'indice de la liste sélectionné
        String login = modelUsers.getElementAt(index);

        //la variable u récupère l'utilisateur en prenant en paramètre le login
        Utilisateur u = chercherParLogin(login);

        //si aucun utilisateur n'est trouvé, on affiche un message
        if (u == null) {
            JOptionPane.showMessageDialog(this, "Utilisateur introuvable.");
            return;
        }
        //on empêche l'admin courant de se supprimer lui-même
        if (adminCourant != null && adminCourant.getLogin() != null) {
            //si le login de l'admin courant colle au login de l'utilisateur à supprimer, on empeche l'utilisateur de se supprimer lui-meme
            if (adminCourant.getLogin().equalsIgnoreCase(login)) {
                JOptionPane.showMessageDialog(this, "Tu ne peux pas te supprimer toi-même.");
                return;
            }
        }

        //si le if avantr n'a pas capté d'anomalie, donc que l'utilisateur veut se suppruimer lui mem par exemple, on demande si l'admin confirme la suppressiobn
        int conf = JOptionPane.showConfirmDialog(
                this,
                "Supprimer l’utilisateur : " + login + " ?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
        );

        //si la réponse est différente de yes, alors on ne fait pas la suppression et on arrete la méthode, on ne passe pas aux instructions suivantes
        if (conf != JOptionPane.YES_OPTION) {
            return;
        }

        //on appelle la méthode pour supprimer l'utilisateur sélectionné
        gestionUsers.supprimer(u);

        //on sauvegarde la suppression dans le fichier txt
        gestionUsers.sauvegarderDansFichier("data/utilisateurs.txt");

        //on rafraichit la liste des utilisateurs pour prendre ne compte le changement depuis le fichier txt
        rafraichirListeUsers();
        JOptionPane.showMessageDialog(this, "Utilisateur supprimé.");

    }//GEN-LAST:event_btnSupprimerAdminUtilisateurActionPerformed

    private void btnDeconnexionAdminUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconnexionAdminUtilisateurActionPerformed
        // TODO add your handling code here:

        // on retourne à la page de connexion et on cache la fentre actuelle
        FenetreConnexion fc = new FenetreConnexion(gestionUsers, catalogue);
        this.setVisible(false);
        fc.setVisible(true);
    }//GEN-LAST:event_btnDeconnexionAdminUtilisateurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterAdminUtilisateur;
    private javax.swing.JButton btnDeconnexionAdminUtilisateur;
    private javax.swing.JButton btnModifierAdminUtilisateur;
    private javax.swing.JButton btnRetourAdminUtilisateur;
    private javax.swing.JButton btnSupprimerAdminUtilisateur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listeAdminUtilisateur;
    private javax.swing.JLabel titreAdminUtilisateur;
    // End of variables declaration//GEN-END:variables
}
