/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_java.UI;

import javax.swing.JFrame;
import projet_java.model.Catalogue;
import projet_java.model.Utilisateur;
import projet_java.service.GestionFavoris;
import projet_java.service.GestionUtilisateurs;

/**
 *
 * @author nabil
 */
//cette page va surtout faire le  lien avec le reste, donc la déconnexion va ramener à la page de connexion, 
//on pourra aussi accéder au x favoris, ajouter un manga manuellement à ses favoris perso et surtout, lancer une recommandatiion !
public class FenetreAccueil extends javax.swing.JFrame {

    //final permet d'^tre sur que quand on arrive dans cet ecran, le catalogue ou l'utilisateur ne changeront pas
    //le private permet que les infos de l'utilisateur connecté ne changent pas, donc l'utilisateur connecté ne changera pas avant déconnexion par exempke
    private final GestionUtilisateurs gestionUsers; //c'est lo'bjet qui gère les utilisateurs
    private final Catalogue catalogue; //le catalogue des mangas
    private final Utilisateur utilisateur; // c'est l'utilisateur qui est connecté

    /**
     * Creates new form FenetreAdmin
     */
    //la fentre d'accueil prendra en argument l'utilisateur connecté, le catalogue de manga et la gestion utilisateur
    public FenetreAccueil(GestionUtilisateurs gu, Catalogue cat, Utilisateur u) {
        initComponents();

        //on affecte les attrubts de l'objet fenetre d'accueil 
        this.gestionUsers = gu;
        this.catalogue = cat;
        this.utilisateur = u;

        //on recharge les favoris de l'utilisateur depuis le fichier au moment de la connexion
        GestionFavoris gf = new GestionFavoris();
        gf.chargerFavorisPour(utilisateur, catalogue);

        //on fait les réglages pour la fenetre d'accueil
        setTitle("Accueil");
        setSize(720, 480);
        setLocation(220, 160);

        //j'ai un doute sur le exit on close ici, ça risque de faire quitter 
        //l'appli entière je pense, j'ai un doute, ttester et voir
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLancerReco = new javax.swing.JButton();
        btnFavoris = new javax.swing.JButton();
        btnDeconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLancerReco.setText("Lancer une reco !");
        btnLancerReco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancerRecoActionPerformed(evt);
            }
        });

        btnFavoris.setText("Mes Favoris");
        btnFavoris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavorisActionPerformed(evt);
            }
        });

        btnDeconnexion.setText("Déconnexion");
        btnDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeconnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFavoris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnLancerReco)
                .addGap(0, 136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFavoris)
                    .addComponent(btnDeconnexion))
                .addGap(69, 69, 69)
                .addComponent(btnLancerReco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFavorisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavorisActionPerformed
        // TODO add your handling code here:

        //on créé la fenetre des favoris, on cache l'actuelle et on affiche celle des favoris
        FenetreFavoris ff = new FenetreFavoris(gestionUsers, catalogue, utilisateur);
        this.setVisible(false); // on cache l’accueil
        ff.setVisible(true);    // on affiche la fenêtre des favoris
    }//GEN-LAST:event_btnFavorisActionPerformed

    private void btnDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconnexionActionPerformed
        // TODO add your handling code here:
        //cliquer sur ce bouton va ramenr à la page de connexion

        // on créé un objet fenetre de connexion, qui va utiliser le catalogue manga et la gestion des utilisateurs
        FenetreConnexion fc = new FenetreConnexion(gestionUsers, catalogue);
        this.setVisible(false); // on cache l’accueil
        fc.setVisible(true);    // on affiche la connexion

    }//GEN-LAST:event_btnDeconnexionActionPerformed

    private void btnLancerRecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancerRecoActionPerformed
        // TODO add your handling code here:

        //meme raisonnement que plus haut, on créé la fenetre vers laquelle on doit aller
        //puis on cache la fentre actuelle et on affiche celle qu'on veut montrer
        FenetreQuestionnaire fq = new FenetreQuestionnaire(gestionUsers, catalogue, utilisateur);
        this.setVisible(false); // on cache l’accueil
        fq.setVisible(true);    // on affiche la fenêtre de questionnaire
    }//GEN-LAST:event_btnLancerRecoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeconnexion;
    private javax.swing.JButton btnFavoris;
    private javax.swing.JButton btnLancerReco;
    // End of variables declaration//GEN-END:variables
}
