/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_java.UI;

import javax.swing.JFrame;
import projet_java.model.Catalogue;
import projet_java.model.Utilisateur;
import projet_java.service.GestionUtilisateurs;

/**
 *
 * @author nabil
 */
public class FenetreAdminMenu extends javax.swing.JFrame {

    //final permet d'^tre sur que quand on arrive dans cet ecran, le catalogue ou l'utilisateur ne changeront pas
    //le private permet que les infos de l'utilisateur connecté ne changent pas, donc l'utilisateur connecté ne changera pas avant déconnexion par exempke
    private final GestionUtilisateurs gestionUsers; //c'est lo'bjet qui gère les utilisateurs
    private final Catalogue catalogue; //le catalogue des mangas
    private final Utilisateur utilisateur; // c'est l'utilisateur qui est connecté
    private final JFrame ecranRetour;

    /**
     * Creates new form FenetreAdminMenu
     */
    public FenetreAdminMenu(GestionUtilisateurs gu, Catalogue cat, Utilisateur u, JFrame retour) {
        initComponents();

        //on affecte les attrubts de l'objet fenetre d'accueil 
        this.gestionUsers = gu;
        this.catalogue = cat;
        this.utilisateur = u;

        //on mémorise la fenetre juste avant, celle qui a ouvert la fiche manga, pour pouvoir revenir ne arrière
        this.ecranRetour = retour;

        //réglages de la fenetre
        //Inutile je pense : setTitle("Menu Administrateur");
        setSize(460, 300);
        setLocation(320, 200);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreMenuAdmin = new javax.swing.JLabel();
        btnCatalogueAdminMenu = new javax.swing.JButton();
        btnDeconnexionAdminMenu = new javax.swing.JButton();
        btnRetourAdminMenu = new javax.swing.JButton();
        btnUtilisateursAdminMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titreMenuAdmin.setText("Menu administrateur");

        btnCatalogueAdminMenu.setText("Utilisateurs");
        btnCatalogueAdminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogueAdminMenuActionPerformed(evt);
            }
        });

        btnDeconnexionAdminMenu.setText("Déconnexion");
        btnDeconnexionAdminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeconnexionAdminMenuActionPerformed(evt);
            }
        });

        btnRetourAdminMenu.setText("Retour");
        btnRetourAdminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourAdminMenuActionPerformed(evt);
            }
        });

        btnUtilisateursAdminMenu.setText("Catalogue");
        btnUtilisateursAdminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtilisateursAdminMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(titreMenuAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(btnDeconnexionAdminMenu))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRetourAdminMenu)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnCatalogueAdminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnUtilisateursAdminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titreMenuAdmin)
                    .addComponent(btnDeconnexionAdminMenu))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatalogueAdminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUtilisateursAdminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnRetourAdminMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeconnexionAdminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconnexionAdminMenuActionPerformed
        // TODO add your handling code here:

        // on retourne à la page de connexion et on cache la fentre actuelle
        FenetreConnexion fc = new FenetreConnexion(gestionUsers, catalogue);
        this.setVisible(false);
        fc.setVisible(true);

    }//GEN-LAST:event_btnDeconnexionAdminMenuActionPerformed

    private void btnCatalogueAdminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogueAdminMenuActionPerformed
        // TODO add your handling code here:

        //on ouvre la fentre d'administration de catalogue, on cache alors le menu et on ouvre la bonne fenetre
        FenetreAdminUtilisateurs f = new FenetreAdminUtilisateurs(gestionUsers, catalogue, utilisateur, this);
        this.setVisible(false);
        f.setVisible(true);


    }//GEN-LAST:event_btnCatalogueAdminMenuActionPerformed

    private void btnRetourAdminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourAdminMenuActionPerformed
        // TODO add your handling code here:

        //on revient à la fenêtre qui a ouvert le menu
        if (ecranRetour != null) {
            this.setVisible(false);//on cache la fenetre actuelle
            ecranRetour.setVisible(true);  //on affiche la fenetre d'avant
        } else {
            // normalement on entrera pas dans ce if mais si jamais j'ai raté un bout de code, en failsafe ça revient à l'accueil
            FenetreAccueil fa = new FenetreAccueil(gestionUsers, catalogue, utilisateur);
            this.setVisible(false);
            fa.setVisible(true);
        }
    }//GEN-LAST:event_btnRetourAdminMenuActionPerformed

    private void btnUtilisateursAdminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilisateursAdminMenuActionPerformed
        // TODO add your handling code here:

        //on ouvre la fentre d'administration des utilisateurs et on cache cette fenetre
        FenetreAdminCatalogue f = new FenetreAdminCatalogue(gestionUsers, catalogue, utilisateur, this);
        this.setVisible(false);
        f.setVisible(true);

    }//GEN-LAST:event_btnUtilisateursAdminMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogueAdminMenu;
    private javax.swing.JButton btnDeconnexionAdminMenu;
    private javax.swing.JButton btnRetourAdminMenu;
    private javax.swing.JButton btnUtilisateursAdminMenu;
    private javax.swing.JLabel titreMenuAdmin;
    // End of variables declaration//GEN-END:variables
}
