/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_java.UI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import projet_java.model.Catalogue;
import projet_java.model.Manga;
import projet_java.model.RecoCritere;
import projet_java.model.Utilisateur;
import projet_java.service.GestionUtilisateurs;
import projet_java.service.RecoSystem;
import java.util.ArrayList;

/**
 *
 * @author nabil
 */
public class FenetreQuestionnaire extends javax.swing.JFrame {

    //final permet d'^tre sur que quand on arrive dans cet ecran, le catalogue ou l'utilisateur ne changeront pas
    //le private permet que les infos de l'utilisateur connecté ne changent pas, donc l'utilisateur connecté ne changera pas avant déconnexion par exempke
    private final GestionUtilisateurs gestionUsers; //c'est lo'bjet qui gère les utilisateurs
    private final Catalogue catalogue; //le catalogue des mangas
    private final Utilisateur utilisateur; // c'est l'utilisateur qui est connecté
    private final RecoSystem reco; // service de reco basé sur le catalogue

    /**
     * Creates new form FenetreQuestionnaire
     */
    public FenetreQuestionnaire(GestionUtilisateurs gu, Catalogue cat, Utilisateur u) {
        initComponents();

        //on affecte les attrubts de l'objet fenetre d'accueil 
        this.gestionUsers = gu;
        this.catalogue = cat;
        this.utilisateur = u;
        this.reco = new RecoSystem(cat); // le service travaille sur le même catalogue

        //réglages de la fenetre
        setTitle("Questionnaire de recommandation");
        setSize(520, 360);
        setLocation(260, 200);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValiderQuestionnaire = new javax.swing.JButton();
        btnRetourQuestionnaire = new javax.swing.JButton();
        LabelGenreQuestionnaire = new javax.swing.JLabel();
        LabelAmbianceQuestionnaire = new javax.swing.JLabel();
        LabelLongueurQuestionnaire = new javax.swing.JLabel();
        LabelUniversQuestionnaire = new javax.swing.JLabel();
        ComboGenre = new javax.swing.JComboBox<>();
        ComboAmbiance = new javax.swing.JComboBox<>();
        ComboLongueur = new javax.swing.JComboBox<>();
        ComboUnivers = new javax.swing.JComboBox<>();
        LabelTypeQuestionnaire = new javax.swing.JLabel();
        ComboType = new javax.swing.JComboBox<>();
        LabelPeriodeQuestionnaire = new javax.swing.JLabel();
        ComboPeriode = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnValiderQuestionnaire.setText("Valider");
        btnValiderQuestionnaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderQuestionnaireActionPerformed(evt);
            }
        });

        btnRetourQuestionnaire.setText("Retour");
        btnRetourQuestionnaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourQuestionnaireActionPerformed(evt);
            }
        });

        LabelGenreQuestionnaire.setText("Genre");

        LabelAmbianceQuestionnaire.setText("Ambiance");

        LabelLongueurQuestionnaire.setText("Longueur");

        LabelUniversQuestionnaire.setText("Univers");

        ComboGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Action", "Aventure", "Comédie", "Dark Fantasy", "Fantastique", "Horreur", "Samurai", "Science-Fiction", "Sport", "Thriller" }));
        ComboGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGenreActionPerformed(evt);
            }
        });

        ComboAmbiance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Apocalyptique", "Cyberpunk", "Dramatique", "Dystopique", "Émouvant", "Énergique", "Épique", "Futuriste", "Humoristique", "Lumineux", "Magique", "Mystérieux", "Occulte", "Psychologique", "Sombre", "Super-héroïque", "Surnaturel", "Tragique", "Violent", "Virtuel" }));

        ComboLongueur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Court", "Long" }));
        ComboLongueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboLongueurActionPerformed(evt);
            }
        });

        ComboUnivers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Allemagne", "Basketball japonais", "École japonaise", "Futur dystopique", "Futur robotisé", "Japon contemporain", "Japon féodal", "Monde démoniaque", "Monde des fléaux", "Monde des héros", "Monde des hunters", "Monde des pirates", "Monde des shinigamis", "Monde industriel", "Monde magique", "Monde médiéval", "Monde ninja", "Monde post-apocalyptique", "Neo-Tokyo", "Royaume de Clover", "Tokyo alternatif", "Tokyo futuriste", "Univers Dragon Ball", "Univers VR", "Volley japonais" }));

        LabelTypeQuestionnaire.setText("Type");

        ComboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Shonen", "Seinen" }));
        ComboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTypeActionPerformed(evt);
            }
        });

        LabelPeriodeQuestionnaire.setText("Période");

        ComboPeriode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Récent (>= 2010)", "Classique (< 2010)" }));
        ComboPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPeriodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LabelGenreQuestionnaire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelAmbianceQuestionnaire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelLongueurQuestionnaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelUniversQuestionnaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTypeQuestionnaire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelPeriodeQuestionnaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(42, 42, 42)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ComboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboAmbiance, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboLongueur, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboUnivers, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnValiderQuestionnaire)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(btnRetourQuestionnaire)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTypeQuestionnaire)
                    .addComponent(ComboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGenreQuestionnaire)
                    .addComponent(ComboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAmbianceQuestionnaire)
                    .addComponent(ComboAmbiance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLongueurQuestionnaire)
                    .addComponent(ComboLongueur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUniversQuestionnaire)
                    .addComponent(ComboUnivers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPeriodeQuestionnaire)
                    .addComponent(ComboPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValiderQuestionnaire)
                    .addComponent(btnRetourQuestionnaire))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboGenreActionPerformed

    private void ComboLongueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboLongueurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboLongueurActionPerformed

    private void btnValiderQuestionnaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderQuestionnaireActionPerformed
        // TODO add your handling code here:

        //on créé des variables string et dedans on va récupérer les selections des jcombobox
        String genreSel = (String) ComboGenre.getSelectedItem();     //"Action" ou " " (donc vide si " ")
        String ambianceSel = (String) ComboAmbiance.getSelectedItem();  //"Sombre" ou " "
        String longueurSel = (String) ComboLongueur.getSelectedItem();  // "Court" / "Long" / " "
        String universSel = (String) ComboUnivers.getSelectedItem();   // "Monde ninja" ou " "
        String typeSel = (String) ComboType.getSelectedItem();
        String periodeSel = (String) ComboPeriode.getSelectedItem();
        //comme je veux manipuler non pas des espaces avec les " ", qui disent que c'est vid,e mais des null, alors je les converti en null si on a juste un espace auy lieu d'un vrai maot, c'est le cas ou l'utilisazteur ne sélectionne rien)
        //donc si qq chose est bien inscrit et que c'est un espace, alors on dit que c'est null 
        if (genreSel != null && genreSel.equals(" ")) {
            genreSel = null;
        }
        if (ambianceSel != null && ambianceSel.equals(" ")) {
            ambianceSel = null;
        }
        if (longueurSel != null && longueurSel.equals(" ")) {
            longueurSel = null;
        }
        if (universSel != null && universSel.equals(" ")) {
            universSel = null;
        }
        if (typeSel != null && typeSel.equals(" ")) {
            typeSel = null;
        }
        if (periodeSel != null && periodeSel.equals(" ")) {
            periodeSel = null;
        }

        //pour la reco, l'un des crtières est la longueur en chapitres d'un manga, donc on va gérer ce critère ci-dessous
        //on comence par créé deux variables qui vont servir à cadrer la longueur en chapitres des mangas pour la reco
        //on les initialise avec ces valeurs qui vont couvrir tous les mangas comme ça si l'utilisateur ne choisi rien 
        //sur la longueur, par défaut ça va ressortir les mangas ayant entre 0 et 999999 chapitres, donc tous !
        int longueurMin = 0; //donc la longueur minimal d'un manga en chapitres
        int longueurMax = 999999; // donc la longueur maximale d'un manga en chapitres

        //si la longueur sélectionnée n'est pas null
        if (longueurSel != null) {
            //si l'utilisateur a choisi court
            if (longueurSel.equalsIgnoreCase("Court")) {
                //on a pris comme critère qu'un manga court fait au maximum 200 chapitres, *
                //il verra alors le smangas qui font 200 chapitres de longueur ua max
                longueurMin = 0;
                longueurMax = 200;   
            } //l'autre cas c'est quil ai choisi long, la fourchette sera différente dans ce cas
            else if (longueurSel.equalsIgnoreCase("Long")) {
                //donc ici on prend les mangas qui faut au moins 200 chapitres, la valeur de longueur 
                //max est une valeur absurdement haute pour ne pas avoir à se soucier de l emodifier encore après
                //en cherchant des infos pour le projetn, j'ai vu qu'il existait des mangas qui comptent 1960 chapitres et meme un qui en 
                //compte 13 780 (Little Rascal Kobo-chan), que je n'ai pas lu mais au vu du nombre de chapitres, j'ai voulu sécuriser la plage max
                longueurMin = 201;
                longueurMax = 999999;
            }
        }

        //on définit les bornes des années pour dire si un manga est classique ou récent
        //là c'est le meme raisonnement, je détrermine une borne supérieure et une borne inférieur par défaut
        //puis je 
        int anneeMin = 0;
        int anneeMax = 9999;
        if (periodeSel != null) {
            if (periodeSel.equalsIgnoreCase("Récent (>= 2010)")) {
                anneeMin = 2010;
                anneeMax = 9999;
            } else if (periodeSel.equalsIgnoreCase("Classique (< 2010)")) {
                anneeMin = 0;
                anneeMax = 2009;
            }
        }

        //on construit l'objet de critère de selection, tous les éléments ici sont facultatif à remplir pour l'utilisateur car il y a une valeur par défaut qui affichera alors tout le catalogue
        RecoCritere crit = new RecoCritere(
                genreSel, // genre (facultatif)
                typeSel, // type (facultatif)
                ambianceSel, // ambiance (facultatif)
                longueurMin, // bornes longueur
                longueurMax,
                universSel, // univers (facultatif)
                anneeMin,
                anneeMax
        );

        //plus qu'à calculer quelles reco à faire
        ArrayList<Manga> resultats = this.reco.recommanderManga(crit);     // on créé une liste de manga qui vont utiliser comme critères ceux saisis par l'utilisateur, c'est cette liste que verra l'utilisateur

        // on met un élément qui va prévenir l'utilisateur du nombre de résultats qui vont ressortir quand il va vlaider, 
//on fait ça avant qu'il clique comme ça il pourra ajuster les filtres pour avoir plus ou moins de résutlatsd
//on créé un int initialisé à 0
        int nb = 0;
//si des reusltats sont retournés, notre variable se verra assigné la taille de laliste, enfin son nombre d'éléments, donc de mangas ici       
        if (resultats != null) {
            nb = resultats.size();
        }

//on créé un autre int indiquant le choix effectué par l'utilisateur et on lui fais choisir s'il veut lmancer la reco ou pas
        int choix = JOptionPane.showConfirmDialog(
                this,
                "Tu auras " + nb + " résultat(s). Continuer ?",
                "Confirmer",
                JOptionPane.YES_NO_OPTION
        );
//si l'utilisateur ne choisi pas oui, alors on arrete la méthode et on retouren sur l'écran de base, enfin on reste sur l'écran mais rien ne se passe
        if (choix != JOptionPane.YES_OPTION) {
            return;
        }

        //on ouvre la fentre de resultats car l'utilisateur a cliqué sur valider
        FenetreResultats fr = new FenetreResultats(gestionUsers, catalogue, utilisateur, resultats, this);
        this.setVisible(false);
        fr.setVisible(true);


    }//GEN-LAST:event_btnValiderQuestionnaireActionPerformed

    private void btnRetourQuestionnaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourQuestionnaireActionPerformed
        // TODO add your handling code here:

        FenetreAccueil fa = new FenetreAccueil(gestionUsers, catalogue, utilisateur);
        this.setVisible(false);
        fa.setVisible(true);
    }//GEN-LAST:event_btnRetourQuestionnaireActionPerformed

    private void ComboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTypeActionPerformed

    private void ComboPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPeriodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPeriodeActionPerformed

    //j'ai supprimé le main, ça faisait planter !

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboAmbiance;
    private javax.swing.JComboBox<String> ComboGenre;
    private javax.swing.JComboBox<String> ComboLongueur;
    private javax.swing.JComboBox<String> ComboPeriode;
    private javax.swing.JComboBox<String> ComboType;
    private javax.swing.JComboBox<String> ComboUnivers;
    private javax.swing.JLabel LabelAmbianceQuestionnaire;
    private javax.swing.JLabel LabelGenreQuestionnaire;
    private javax.swing.JLabel LabelLongueurQuestionnaire;
    private javax.swing.JLabel LabelPeriodeQuestionnaire;
    private javax.swing.JLabel LabelTypeQuestionnaire;
    private javax.swing.JLabel LabelUniversQuestionnaire;
    private javax.swing.JButton btnRetourQuestionnaire;
    private javax.swing.JButton btnValiderQuestionnaire;
    // End of variables declaration//GEN-END:variables
}
