/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_java.UI;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import projet_java.model.Catalogue;
import projet_java.model.Manga;
import projet_java.model.Utilisateur;
import projet_java.service.GestionUtilisateurs;

/**
 *
 * @author nabil
 */
public class FenetreAdminCatalogue extends javax.swing.JFrame {
//final permet d'^tre sur que quand on arrive dans cet ecran, le catalogue ou l'utilisateur ne changeront pas
    //le private permet que les infos de l'utilisateur connecté ne changent pas, donc l'utilisateur connecté ne changera pas avant déconnexion par exempke

    private final Catalogue catalogue; //le catalogue des mangas
    private final Utilisateur adminCourant;  // c'est l'utilisateur qui est connecté, ici un admin, on s'en servira poiur qu'il ne puisse pas se supprimer lui-m
    private final JFrame ecranRetour;
    private final GestionUtilisateurs gestionUsers;

    //on créé un model de liste pour la liste des mangas du catalogue,on l'appliquera a notre liste     
    private final DefaultListModel<String> modelMangas = new DefaultListModel<>();

    /**
     * Creates new form FenetreAdminCatalogue
     */
    public FenetreAdminCatalogue(GestionUtilisateurs users, Catalogue cat, Utilisateur admin, JFrame retour) {
        initComponents();

        //on affecte les attrubts de l'objet fenetre d'accueil 
        this.catalogue = cat;
        this.adminCourant = admin;
        this.gestionUsers = users;

        //on mémorise la fenetre juste avant, celle qui a ouvert la fiche manga, pour pouvoir revenir ne arrière
        this.ecranRetour = retour;

        //réglages de l'écran
        //setTitle("Administration du catalogue");
        setSize(620, 420);
        setLocation(300, 200);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        //lier le model créé à la liste
        listeAdminCatalogue.setModel(modelMangas);
        rafraichirListeMangas();

    }

    //on charge les données du catalogue dans la liste 
    private void rafraichirListeMangas() {
        //on vide la liste
        modelMangas.removeAllElements();
        //on parcours chaque manga dans le catalogue
        for (Manga m : catalogue.getBase()) {
            //on créé un string qui va prendre tour à tour le titre de chaque manga de la liste
            String titre = m.getTitre();
            //si le titre est bien renseigné
            if (titre != null && titre.length() > 0) {
                //on l'ajoute à la liste
                modelMangas.addElement(titre);
            } //sinon on ajoute l'élément en signalanrt qu'il n'avait pas de titre indiqué
            else {
                modelMangas.addElement("Pas de titre renseigné");
            }
        }
    }

    //methode pour rechercher un manga par titre, elle vient de la classe catalogue
    private Manga chercherParTitre(String titre) {
        //si pas de titre, rien ne se passe on aarrete la methode
        if (titre == null) {
            return null;
        }
        //sinon on renvoi le manga trouvé grace à son titre passé en paramètre
        return catalogue.rechercherParTitre(titre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreAdminCatalogue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeAdminCatalogue = new javax.swing.JList<>();
        btnDeconnexionAdminCatalogue = new javax.swing.JButton();
        btnRetourAdminCatalogue = new javax.swing.JButton();
        btnAjoutAdminCatalogue = new javax.swing.JButton();
        btnSupprimerAdminCatalogue = new javax.swing.JButton();
        btnModifierAdminCatalogue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titreAdminCatalogue.setText("Administration du catalogue");

        listeAdminCatalogue.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listeAdminCatalogue);

        btnDeconnexionAdminCatalogue.setText("Déconnexion");
        btnDeconnexionAdminCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeconnexionAdminCatalogueActionPerformed(evt);
            }
        });

        btnRetourAdminCatalogue.setText("Retour");
        btnRetourAdminCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourAdminCatalogueActionPerformed(evt);
            }
        });

        btnAjoutAdminCatalogue.setText("Ajouter");
        btnAjoutAdminCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutAdminCatalogueActionPerformed(evt);
            }
        });

        btnSupprimerAdminCatalogue.setText("Supprimer");
        btnSupprimerAdminCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerAdminCatalogueActionPerformed(evt);
            }
        });

        btnModifierAdminCatalogue.setText("Modifier");
        btnModifierAdminCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierAdminCatalogueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(titreAdminCatalogue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeconnexionAdminCatalogue))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRetourAdminCatalogue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSupprimerAdminCatalogue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModifierAdminCatalogue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAjoutAdminCatalogue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titreAdminCatalogue)
                    .addComponent(btnDeconnexionAdminCatalogue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnAjoutAdminCatalogue)
                        .addGap(28, 28, 28)
                        .addComponent(btnModifierAdminCatalogue)
                        .addGap(31, 31, 31)
                        .addComponent(btnSupprimerAdminCatalogue)
                        .addGap(42, 42, 42)
                        .addComponent(btnRetourAdminCatalogue)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeconnexionAdminCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconnexionAdminCatalogueActionPerformed
        // TODO add your handling code here:

// on retourne à la page de connexion et on cache la fentre actuelle
        FenetreConnexion fc = new FenetreConnexion(gestionUsers, catalogue);
        this.setVisible(false);
        fc.setVisible(true);
    }//GEN-LAST:event_btnDeconnexionAdminCatalogueActionPerformed

    private void btnAjoutAdminCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutAdminCatalogueActionPerformed
        // TODO add your handling code here:

        //on créé les différentes variables pour les infos du manga, donc le titre, 
        //puis l'auteur, le type, etc, cetains champs seront de la saisie de texte mais pour certains ce sera un choix parmis différentes options possibles
        String titre = JOptionPane.showInputDialog(this, "Titre :");

//si la siasie n'est pas bonne, on arrete la methode, rien ne se passe
        if (titre == null || titre.length() == 0) {
            return;
        }
        //on gère aussi le cas ou u nmanga du meme nom existe deja, on le met pour 
        //le titre car c'est un critère discrimiant mais pour l'auteur on fera pas ça, un meme auteur peut avoir écrit plusieurs mangas
        if (chercherParTitre(titre) != null) {
            JOptionPane.showMessageDialog(this, "Un manga avec ce titre existe déjà.");
            return;
        }

        //meme raisonnement que ci-dessus, saisie du nom de l'auteur mais sans controle d'unicité car un auteur peut ecrire plusieurs mangas
        String auteur = JOptionPane.showInputDialog(this, "Auteur :");
        if (auteur == null || auteur.length() == 0) {
            return;
        }

        //pareil, on fait saisir chaque info du manga
        String type = JOptionPane.showInputDialog(this, "Type (Shonen/Seinen...) :");
        String genre = JOptionPane.showInputDialog(this, "Genre :");
        String ambiance = JOptionPane.showInputDialog(this, "Ambiance :");
        String univers = JOptionPane.showInputDialog(this, "Univers :");

        //pour le sint, on devra les convertir de string à int, on va parseint pour ça
        String saisieChapitresParus = JOptionPane.showInputDialog(this, "Longueur en nombre de chapitres parus :");
        //on créé un int longueur qui indiquera le nombre de chapitres parus
        int chapitresParus = 0;
        //si la saisie est bien effectuée (on veut une saisie,; int ou pas, on s'en fiche 
        //ici car on va s'occuper de gérer les caractères invalides dans la boucle
        if (saisieChapitresParus != null && saisieChapitresParus.length() > 0) {
            //on créé un booléen permettant de savoir si seulement des chiffres ont été saisis ou pas
            boolean saisieok = true;
            //on parcourt la saisie de l'utilisateur
            for (int i = 0; i < saisieChapitresParus.length(); i++) {
                //si un seul des caractères saisis est autre chose qu'un chiffre 
                //compris entre 0 et 9 inclus, la saisie est invvalide et le booléen passera à false
                char c = saisieChapitresParus.charAt(i);
                //ici on a mis des guillemets car on compare les chiffres comme des caractères, 
                //c'est donc leur code ascii qui sera comparé, permettant d'évacuer tout ce qui ne va pas dan,s l'intervalle !
                if (c < '0' || c > '9') {
                    saisieok = false;
                }
            }
            //si la saisie ne contient effectivemment que des chiffres, on fait la conversion en int
            if (saisieok) {
                //enfin, longueur reçoit en int la saisie du nombre de chapitres parus
                chapitresParus = Integer.parseInt(saisieChapitresParus);
            }
        }

        //pour les années, le fonctionnement sera axactement le meme que pour le nombre de chapitres parus ci-dessus
        String saisieAnneeSortie = JOptionPane.showInputDialog(this, "Année de sortie (nombre) :");
        int anneeSortie = 0;
        if (saisieAnneeSortie != null && saisieAnneeSortie.length() > 0) {
            boolean ok = true;
            for (int i = 0; i < saisieAnneeSortie.length(); i++) {
                char c = saisieAnneeSortie.charAt(i);
                if (c < '0' || c > '9') {
                    ok = false;
                }
            }
            if (ok) {
                anneeSortie = Integer.parseInt(saisieAnneeSortie);
            }
        }

        //pour le synopsis, c'est juste une saisie de texte normale
        String synopsis = JOptionPane.showInputDialog(this, "Synopsis :");

        //enfin pour l'image, on peut faire saisir le chemin vers une image, comme c'est l'admin, 
        //on part du principe que celui-ci a toutes les infos lors de l'ajout d'un manga, il mettra 
        //donc tout et aura une image sous la main, qu'il rangera dans le bon 
        //dossier pour qu'il soit accessible pour le programme
        String image = JOptionPane.showInputDialog(this, "Chemin image :");

        //on crée l’objet manga avec les infos saisies
        Manga nouveau = new Manga(
                titre,
                auteur,
                anneeSortie,
                genre,
                type,
                ambiance,
                chapitresParus,
                univers,
                synopsis,
                image
        );

//on ajoute le manga créé au catalogue et on récupère le r
        boolean ajoutOk = catalogue.ajouterManga(nouveau);

// sauvegarder et rafraîchir si ajoutOk vaut true, donc si l'appel de la methode 
//ajouterManga a bien réussi à ajouter le manga au catalogue
        if (ajoutOk) {
            //si l'ajout a réussi, on sauvegarde le manga dans le ficher txt
            catalogue.sauvegarderDansFichier("data/catalogue.txt");

            //on met à jour la liste pour afficher des infos à jour
            rafraichirListeMangas();

            //on affiche un message 
            JOptionPane.showMessageDialog(this, "Manga ajouté avec succès !");
        } //si l'ajout n'a pas réussi, on affiche un message le disant à l'admin
        else {
            JOptionPane.showMessageDialog(this, "Échec de l’ajout (vérifiez si le titre existe déjà)");
        }

    }//GEN-LAST:event_btnAjoutAdminCatalogueActionPerformed

    private void btnModifierAdminCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierAdminCatalogueActionPerformed
        // TODO add your handling code here:

        //on créé un indice qui sera celui du manga sélectionné dasn la liste
        int index = listeAdminCatalogue.getSelectedIndex();
        //idem que pour le reste, -1 si rien n'est selectionné, différent de -1 azutrement
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Sélectionne un manga.");
            return;
        }

        //on créé un string qui prendra le titre du manga séolectionné
        String titreSel = modelMangas.getElementAt(index);
        //on créé une variable de type manga qui désignera l'ancien manga, enfin le manga tel qu'il est de base dans le catalogue, on veut modifier ses infos
        Manga ancien = chercherParTitre(titreSel);

        //si pas de manga trouvé, on affiche un message
        if (ancien == null) {
            JOptionPane.showMessageDialog(this, "Manga introuvable.");
            return;
        }

        //si le if n'a rien capté, alors un amnga a bien été trouvé, on doit saisir les nouvelles infos donc
        //on commence par le titre
        //on créé une variable qui va stocker le titre saisi par l'admin, s'il ne saisi rien et appui su rentrée direct, le titre reste inchangé
        String saisieTitre = JOptionPane.showInputDialog(this,
                "Ancien titre : " + ancien.getTitre()
                + "\nTapez le nouveau titre (Appuyez sur Entrée pour laisser le titre tel quel)");

        //on créé une autre variable qui, elle, stocke le titre de base du manga, ça permet de ne pas perdre le titre du manga si la saisie de saisie titre est vide
        String valeurTitre = ancien.getTitre(); // par défaut on garde l’ancien
        //si la saisie du titre n'est pas valide, on garde juste l'ancien titre, o n n'entre pas dans ce if
        if (saisieTitre != null && saisieTitre.length() > 0) {
            //si la saisie est bonne, alors le titre qui sera affecté au manga est le titre saisi par l'amdin
            valeurTitre = saisieTitre; // on remplace si saisie non vide
        }

        //on vérifie qu'il n y'a pas deja un manga du meme titre dans le catalogue : 
        //si le titre a été changé, donc saisie titre est différent de valeur titre
        if ((valeurTitre.equalsIgnoreCase(ancien.getTitre())) == false) {
            //si valeur titre, donc qui a été affecté avec le contenu de saisi titre, c'est donc le nouveau titre si une saisie a bvien été faite
            //alors on utilise la methode de recherche de manga par titre pour vérififer si un autre manga du meme  nom n'existe pas deja dans le catalogue
            if (chercherParTitre(valeurTitre) != null) {
                //si tel est le cas, on renvoie un message le disant à l'admin et on arrete la methode
                JOptionPane.showMessageDialog(this, "Un manga avec ce titre existe déjà.");
                return;
            }
        }

        //on passe à l'auteur, le raisonnement est le meme avec deux variables, uen 
        //pour la saisie et une pour la valeur de base, valeur de base qui se verra changée si une saise a bien été faite
        String saisieAuteur = JOptionPane.showInputDialog(this,
                "Ancien auteur : " + ancien.getAuteur()
                + "\nTapez le nouvel auteur (laisser vide = inchangé)");

        //idem que plus haut, par défaut cette variable prend la valeur de base de l'auter
        String valeurAuteur = ancien.getAuteur();
        if (saisieAuteur != null && saisieAuteur.length() > 0) {
            valeurAuteur = saisieAuteur;
        }

//on  passe au type, le raisonnmeent est ausi le meme, pas besoin de plus de ocmmentaires je pense
        String saisieType = JOptionPane.showInputDialog(this,
                "Ancien type : " + ancien.getType()
                + "\nTapez le nouveau type (laisser vide = inchangé)");

        String valeurType = ancien.getType();
        if (saisieType != null && saisieType.length() > 0) {
            valeurType = saisieType;
        }

//idem avec le genre
        String saisieGenre = JOptionPane.showInputDialog(this,
                "Ancien genre : " + ancien.getGenre()
                + "\nTapez le nouveau genre (laisser vide = inchangé)");

        String valeurGenre = ancien.getGenre();
        if (saisieGenre != null && saisieGenre.length() > 0) {
            valeurGenre = saisieGenre;
        }

//pareil pour l'ambiance
        String saisieAmbiance = JOptionPane.showInputDialog(this,
                "Ancienne ambiance : " + ancien.getAmbiance()
                + "\nTapez la nouvelle ambiance (laisser vide = inchangé)");

        String valeurAmbiance = ancien.getAmbiance();
        if (saisieAmbiance != null && saisieAmbiance.length() > 0) {
            valeurAmbiance = saisieAmbiance;
        }

//et pour l'univers
        String saisieUnivers = JOptionPane.showInputDialog(this,
                "Ancien univers : " + ancien.getUnivers()
                + "\nTapez le nouvel univers (laisser vide = inchangé)");

        String valeurUnivers = ancien.getUnivers();
        if (saisieUnivers != null && saisieUnivers.length() > 0) {
            valeurUnivers = saisieUnivers;
        }

        //pour les int, donc  la longueur en chapitres et pour l'année de débviut de parution du manga, on doit convertir ne int
        String saisieLongueur = JOptionPane.showInputDialog(this,
                "Ancienne longueur : " + ancien.getLongueurChapitres()
                + "\nTapez la nouvelle longueur (laisser vide = inchangé)");

        //on créé un int qui sera affecté avec la valeur de base du nombre de chapitres
        int valeurLongueur = ancien.getLongueurChapitres();

        //on controle qu'une saisie a bien été faite
        if (saisieLongueur != null && saisieLongueur.length() > 0) {

            //on créé un booléen disant si la saisie est ok ou pas, on dit que oui par défaut
            boolean saisieOk = true;

            //on controle char par char comme on l'a deja fait ailleurs, en comparant les 
            //caractères des chifres de 0 à 9 compris, on saura si les caractères de la saisie sont valides grace à leur code ascii
            for (int i = 0; i < saisieLongueur.length(); i++) {
                //char c c'est le caractère en cours
                char c = saisieLongueur.charAt(i);
                //si ce caractère a un codee ascii comopris entre ceux de 0 et 9, c'est valide
                if (c < '0' || c > '9') {
                    //sinon, on entre dans ce if et le booléen passe à false
                    saisieOk = false;
                }
            }
            //si la saisie est bonne, on converti en int et on affecte à la variable qui sera assignée au manga 
            if (saisieOk) {
                valeurLongueur = Integer.parseInt(saisieLongueur);
            }
        }

//on fait exactement pareil pour l'année, pas besoin de recommenter je pense
        String saisieAnnee = JOptionPane.showInputDialog(this,
                "Ancienne année : " + ancien.getAnneeSortie()
                + "\nTapez la nouvelle année (laisser vide = inchangé)");

        int valeurAnnee = ancien.getAnneeSortie();
        if (saisieAnnee != null && saisieAnnee.length() > 0) {
            boolean saisieOk = true;
            for (int i = 0; i < saisieAnnee.length(); i++) {
                char c = saisieAnnee.charAt(i);
                if (c < '0' || c > '9') {
                    saisieOk = false;
                }
            }
            if (saisieOk) {
                valeurAnnee = Integer.parseInt(saisieAnnee);
            }
        }

        //on repasse aux autres string 
        //pour le synopssi, enfin la description, pareil que pour l'auteru par exmeple, on  récupère la siaise, le synopsis 
        //deja existant et on vérifie si une saise est faite, si oui on rempalce la valeur de base par celle saisie
        String saisieDescription = JOptionPane.showInputDialog(this,
                "Ancien synopsis : " + ancien.getDescription()
                + "\nTapez le nouveau synopsis (laisser vide = inchangé)");

        String valeurDescription = ancien.getDescription();
        if (saisieDescription != null && saisieDescription.length() > 0) {
            valeurDescription = saisieDescription;
        }

//idem pour image, ici on indique le chemin
        String saisieImage = JOptionPane.showInputDialog(this,
                "Ancien chemin image : " + ancien.getImage()
                + "\nTapez le nouveau chemin image (laisser vide = inchangé)");

        String valeurImage = ancien.getImage();
        if (saisieImage != null && saisieImage.length() > 0) {
            valeurImage = saisieImage;
        }

        //grace aux saisies faites ci-dessus, on créé l'objet manga mis à jour avec ces infos
        Manga modifie = new Manga(
                valeurTitre,
                valeurAuteur,
                valeurAnnee,
                valeurGenre,
                valeurType,
                valeurAmbiance,
                valeurLongueur,
                valeurUnivers,
                valeurDescription,
                valeurImage
        );

        //on rempalce le manga existant par le nouveau créé
        //on commence par retirer le manga existant
        catalogue.retirerManga(ancien);

        //on créé un booléen indiquant si l'ajout du manga au catalogue a bien été faite
        //elle prendra pour valeur de ce que renvoie la methode d'ajout de manga qui existe deja dans la classe catalogue
        boolean ajoutMangaOk = catalogue.ajouterManga(modifie);
        //s"il ajout du manga a échoué
        if (ajoutMangaOk == false) {
            //si l'ajout a échoué, en secours on remet le manga qui existait deja de base pour ne pas le perdre
            catalogue.ajouterManga(ancien);
            //on affiche alors un mùessage prévenant l'admùin que ça avait échoué et on arrete la methode
            JOptionPane.showMessageDialog(this, "Échec de la modification.");
            return;
        }

//on sauvegarde la mise à jour dans le fichier txt qui contient les infos du catalogue
        catalogue.sauvegarderDansFichier("data/catalogue.txt");

        //on remet à jour la liste des mangas qui s'affichera dans l'appli
        rafraichirListeMangas();

        //on affiche un message prévenant quer tout s'est bien passé pour la modification !
        JOptionPane.showMessageDialog(this, "Modification effectuée.");
    }//GEN-LAST:event_btnModifierAdminCatalogueActionPerformed

    private void btnSupprimerAdminCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerAdminCatalogueActionPerformed
        // TODO add your handling code here:

//on créé une variable qui va récupérer l'incdice de l'élément sélectionné dans la liste
        int index = listeAdminCatalogue.getSelectedIndex();
//par défaut l'indice vaut -1, donc si qq chose a été sélectionné, l'indice sera différent de -1        
        if (index == -1) {
//dans le cas ou l'index vaut -1, rien n'a été sélectionné           
            JOptionPane.showMessageDialog(this, "Sélectionne un manga.");
//on arreter la methode car rien ne se passe            
            return;
        }

        //on créé un string qui va récupérer le titre du manga sélectioné dans la lsite
        String titreSel = modelMangas.getElementAt(index);
//on créé une variable de type manga m qui sera affecté par le manga trouvé par la methode de recherche par titre         
        Manga m = chercherParTitre(titreSel);
//si aucun manga n'est trouvé, rien ne se passe et un messsage l'indiquant s'affiche        
        if (m == null) {
            JOptionPane.showMessageDialog(this, "Manga introuvable.");
            return;
        }

        //on créé uyn int qui va récupérer le résultat de la saisie permettant de savoir si on supprime bien le manga
        int confirmerSuppression = JOptionPane.showConfirmDialog(
                this,
                "Supprimer : " + titreSel + " ?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
        );
//si la saisie est différente de yes, alors on considère que la suppression n'est pas confirmée, donc on arrete la methode        
        if (confirmerSuppression != JOptionPane.YES_OPTION) {
            return;
        }

//on peut, comme on a passé tous les if de controle, procéder à la suppression
//on appelle la methode de suprpession du catalogue qui est dans la classe catalogue        
        catalogue.retirerManga(m);
//puis la methode de sauvegarde pour que le catalogue soit bien mis à jour et que quand je relance l'appli, le manga supprimé ne réapparaitra pas       
        catalogue.sauvegarderDansFichier("data/catalogue.txt");
//enfin, on met à jour la liste des mangas  qui va s'afficher dans l'appli pour l'utilisateru       
        rafraichirListeMangas();
//enfin, un  message de confirmation de lma suppresion du manga apparait       
        JOptionPane.showMessageDialog(this, "Manga supprimé.");

    }//GEN-LAST:event_btnSupprimerAdminCatalogueActionPerformed

    private void btnRetourAdminCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourAdminCatalogueActionPerformed
        // TODO add your handling code here:

        //on revient à la fenêtre qui a ouvert le menu
        if (ecranRetour != null) {
            this.setVisible(false);//on cache la fenetre actuelle
            ecranRetour.setVisible(true);  //on affiche la fenetre d'avant
        } else {
            // normalement on entrera pas dans ce if mais si jamais j'ai raté un bout de code, en failsafe ça revient à l'accueil
            FenetreAdminMenu fa = new FenetreAdminMenu(gestionUsers, catalogue, adminCourant, null);
            this.setVisible(false);
            fa.setVisible(true);
        }
    }//GEN-LAST:event_btnRetourAdminCatalogueActionPerformed

    //y avait un main mais j'ai supprimé car ça provoque des erreurs
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutAdminCatalogue;
    private javax.swing.JButton btnDeconnexionAdminCatalogue;
    private javax.swing.JButton btnModifierAdminCatalogue;
    private javax.swing.JButton btnRetourAdminCatalogue;
    private javax.swing.JButton btnSupprimerAdminCatalogue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listeAdminCatalogue;
    private javax.swing.JLabel titreAdminCatalogue;
    // End of variables declaration//GEN-END:variables
}
