/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_java.UI;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import projet_java.model.Catalogue;
import projet_java.model.Manga;
import projet_java.model.Utilisateur;
import projet_java.service.GestionFavoris;
import projet_java.service.GestionUtilisateurs;

/**
 *
 * @author nabil
 */
public class FenetreFavoris extends javax.swing.JFrame {

    //final permet d'^tre sur que quand on arrive dans cet ecran, le catalogue ou l'utilisateur ne changeront pas
    //le private permet que les infos de l'utilisateur connecté ne changent pas, donc l'utilisateur connecté ne changera pas avant déconnexion par exempke
    private final GestionUtilisateurs gestionUsers;
    private final Catalogue catalogue;
    private final Utilisateur utilisateur;

    //model de la jliste pour les favoris, on créé une liste 
    private final DefaultListModel<String> modelFavoris = new DefaultListModel<>();

    /**
     * Creates new form FenetreFavoris
     */
    public FenetreFavoris(GestionUtilisateurs gu, Catalogue cat, Utilisateur u) {
        initComponents();

        //on affecte les attrubts de l'objet fenetre d'accueil 
        this.gestionUsers = gu;
        this.catalogue = cat;
        this.utilisateur = u;

        //on lie notre jliste à notre model pour liste de favoris
        listFavoris.setModel(modelFavoris);

        //réglages de la fenetre
        setTitle("Mes favoris");
        setSize(520, 360);
        setLocation(260, 200);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        //boucle de remplissage de la liste, on appelle la méthode pour obtenur les favoris d'un utilisateur
        for (Manga m : utilisateur.getFavoris()) {         // Utilisateur.getFavoris()
            if (m != null && m.getTitre() != null) {       // Manga.getTitre()
                modelFavoris.addElement(m.getTitre());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnVoirMangaFavoris = new javax.swing.JButton();
        btnAjouterManuel = new javax.swing.JButton();
        btnRetirer = new javax.swing.JButton();
        btnRetourFavoris = new javax.swing.JButton();
        scrollFavoris = new javax.swing.JScrollPane();
        listFavoris = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mes favoris");

        btnVoirMangaFavoris.setText("Voir le manga");
        btnVoirMangaFavoris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoirMangaFavorisActionPerformed(evt);
            }
        });

        btnAjouterManuel.setText("Ajouter");
        btnAjouterManuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterManuelActionPerformed(evt);
            }
        });

        btnRetirer.setText("Retirer");
        btnRetirer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirerActionPerformed(evt);
            }
        });

        btnRetourFavoris.setText("Retour");
        btnRetourFavoris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourFavorisActionPerformed(evt);
            }
        });

        listFavoris.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollFavoris.setViewportView(listFavoris);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRetirer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRetourFavoris))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoirMangaFavoris)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(btnAjouterManuel))
                    .addComponent(scrollFavoris))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(scrollFavoris, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoirMangaFavoris)
                    .addComponent(btnAjouterManuel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirer)
                    .addComponent(btnRetourFavoris))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoirMangaFavorisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoirMangaFavorisActionPerformed
        // TODO add your handling code here:

        //on créé un string titre qui va récupérer l'élément de lal liste qui a été sélectionné
        String titre = listFavoris.getSelectedValue();
//si titre est null ,donc aucun manga sélectionné, on affiche un message et on retourne sur la page de favoris        
        if (titre == null) {
            JOptionPane.showMessageDialog(this, "Sélectionne un manga d’abord.");
            return;
        }

        //on créé un objet manga, qui sera le l resultat de la methode qui cherche un manga parmi les favoris d'un utilisateur par titre 
        Manga m = utilisateur.chercherFavoriParTitre(titre);
        //si aucun manga n'est renvoyé, on rentre dans ce if car on ne l'a pas trouvé dans les favoris d'un utilisateur, on cherche alors dans le catalogue global
        if (m == null) {
            //le manga m se verra affecté avec le manga trouvé par la fonction de recherche par titre dans le catalogue global de l'appli
            m = catalogue.rechercherParTitre(titre);

        }
//par contre, si aucun manga n'est trouvé , on affiche un message le disant car on peut pas afficher la fiche dumanga, on retourne alors sur la feetre favoris
        if (m == null) {
            JOptionPane.showMessageDialog(this, "Impossible de retrouver \"" + titre + "\".");
            return;
        }


        /*
//si la non plus, aucun mlanga n'est trouvé, on affiche un  message prévenant l'utilisateur
            if (m == null) {
               
                
                
                JOptionPane.showMessageDialog(this, "Impossible de retrouver \"" + titre + "\".");
                //on interrompt la méthode car on n'a pas trouvé le manga pour lequel on veut 
                return;
         */
        //si aucun des if n'a chopé d'anomalie, alors on peut afficher la page fiche du manga sur lequel l'utilisateur a cliqué
        //en paramètre, on ajout m l'objet manga du manga recherché
        FenetreFicheManga ffm = new FenetreFicheManga(gestionUsers, catalogue, utilisateur, m, this);
        this.setVisible(false);
        ffm.setVisible(true);


    }//GEN-LAST:event_btnVoirMangaFavorisActionPerformed

    private void btnAjouterManuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterManuelActionPerformed
        // TODO add your handling code here:

        // on créé un string titre, l'utilisateur va saisir manuellement le manga qu'il veut ajouter
        String titre = JOptionPane.showInputDialog(this, "Titre exact du manga à ajouter :");
        // si l'utilisateur ne saisi rien, on arrete la méthode, en d'autres mots, il appuie sur le bouton et rien ne se passe, on retourne sur la fentre favoris
        if (titre == null || titre.length() == 0) {
            return;
        }

        //l'utilisateur n'a pas accès au catalogue global du site, donc s'il a voulu ajouter un manga deja présent dans le catalogue de l'appli, on lui renvoie le manga ne question
        Manga m = catalogue.rechercherParTitre(titre);
        //si la recherche du manga par titre dans le catalogue global ne donne rien, on lui permet de l'ajuter
        if (m == null) {

            // on vérifie malgré tout s'il n'est pas déjà dans les favoris en comparant par titre
            if (utilisateur.chercherFavoriParTitre(titre) != null) {
                //si c'est le cas, on affiche un message et return pour arreter lamethode et revenir sur l'ecran des favoris
                JOptionPane.showMessageDialog(this, "Déjà dans tes favoris.");
                return;
            }

            //si le if au-dessus n'a rien capté, on propose de créer un favoris hors catalogue de l'appli, ce ne sera un ajout effectif que pour l'utilisateur connecté, les autres et le catalogue du site n'auront pas de changement
            //on créé une variable int qui va recevoir en valeur la réponse de l'utilisateur
            int choix = JOptionPane.showConfirmDialog(
                    this,
                    "Ce titre n'existe pas dans le catalogue.\nVoulez-vous créer un favori 'hors catalogue' ?",
                    "Créer un favori local",
                    JOptionPane.YES_NO_OPTION
            );
            //si l'utilisateur fait un choix différent du yes, alors on arrete la methode car l'utyilisateur ne veut pas ajouter de manga
            if (choix != JOptionPane.YES_OPTION) {
                return;
            }

            //si le if juste avant n'a rien capté, l'utilisateur a choisi yes, il veut donc créer un manga, on lui fait saisir un minimum d'infos pour ne pas etre contraignant, donc titre, auteur et une descritpion courte
            //on créé un string auteur et on récupère la saisie de l'utilisateur
            String auteur = JOptionPane.showInputDialog(this, "Auteur :");
            //si la saisie est mauvaise, donc l'utilisateur ne tape rien par exemple, on arrete la methode
            if (auteur == null || auteur.length() == 0) {
                return;
            }

            //meme logique que pour l'auteur ci-dessus
            String desc = JOptionPane.showInputDialog(this, "Description (courte) :");
            if (desc == null || desc.length() == 0) {
                return;
            }

            // on créé un objet manga avec les infos récupérées
            //on met 0 en année par défaut car pas renseigné mais ça reste un int
            m = new Manga(titre, auteur, 0, "Non renseigné");
            //on appelle notre setter qui est dans la classe manga
            m.setDescription(desc);

            //on ajoute le manga dans le catalogue et on le sauvegarde dans le txt
            //on créé un booléen qui va récupérer le résultat de la methode d'ajout du  manga
            boolean ajoutManuelOk = catalogue.ajouterManga(m);
            //si l'ajout a reussi, donc si elle renvoie true, alors on sauvegarde le manga dans le fichier txt dfu catalogue
            if (ajoutManuelOk == true) {
                catalogue.sauvegarderDansFichier("data/catalogue.txt");
            }
        } //en revanche, si le manga est deja trouvé dans les favoris
        else {

            //si le if n'a rien capté, alors le manga est bien dans le catalogue
            //on vérifie donc si le manga n'est pas deja dans les favoris de l'utilisateur
            //si le manga est trouvé dans les favoris
            if (utilisateur.chercherFavoriParTitre(titre) != null) {
                //on renvoie un mlessage disant qu'il y est deja
                JOptionPane.showMessageDialog(this, "Déjà dans tes favoris.");
                //on peut arreter l améthode
                return;
            }
            //si le manga n'est pas deja dans les favoris, on le sauvegarde il s'ajoute aussi aux favoris de l'utilisateur et au catalogue 
            catalogue.sauvegarderDansFichier("data/catalogue.txt");

        }

        //enfin, si le manga est trouvé dans le catalogue et pas dans les favoris, alors on l'ajoute aux favoris de l'utilisateur
        //j'appelle la mehode permettant d'ajouter un favoris pour un utilisateur, en prenant comme argument le manga que je veux passer  en favoris
        utilisateur.ajouterFavori(m);

        //on ajoute le favori aux...bah favoris de l'utilisateur, comme je passe pas par l'écran de reco ici, ça marchait pas pour la mise à jour du fichier txt, mtn ça devrait fonctionenr !
        GestionFavoris gf = new GestionFavoris();
        gf.ajouterFavori(utilisateur, m);

        //on vérifie si le titre existe déjà dans la liste des favoris affichés
        //on créé un booléen disant si le manga ajouté est déjà présent ou pas
        boolean dejaPresent = false;

        //on parcours la liste des favoris de l'utilisateur
        for (int i = 0; i < modelFavoris.size(); i++) {
            //on créé un string qui prendra la valeur du manga au ième élément, 
            //ça prendra donc la valeur de chaque élément successivement
            String titreExistant = modelFavoris.getElementAt(i);

            //si le titre en, cours de l aliste auquel on compare la saisie de l'utilisateur pour l'ajout d'un manga
            //renvoie true, alors le booléen indiquant si si le manga est deja présent devient true
            if (titreExistant.equalsIgnoreCase(m.getTitre())) {
                dejaPresent = true;
            }
        }

        //si le if juste avant n'a pas capté le fait que le manga est deja dans les favoris, alors on ajoute l'élément à la liste
        if (dejaPresent == false) {
            //l'utilisateur a bien eu un favori ajouté en plus, on modifie donc la liste qui sera sur l'appli en conséquence

            modelFavoris.addElement(m.getTitre());
        }

        //on affiche donc un message permettant de dire à l'utilisazteur que le manga a été ajouté !
        JOptionPane.showMessageDialog(this, "Ajouté aux favoris : " + m.getTitre());

    }//GEN-LAST:event_btnAjouterManuelActionPerformed

    private void btnRetirerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirerActionPerformed
        // TODO add your handling code here:

//on créé un int, il indiquera la valeur dans la lsite du manga selectionné
        int index = listFavoris.getSelectedIndex();
//on gère le cas ou rien n'est sélectionné, getselectedindex renvoie alors -1    
        if (index == -1) {
//on affiche un message et on retourne sur la page des favoris        
            JOptionPane.showMessageDialog(this, "Sélectionne un manga à retirer.");
            return;
        }

//si qq chose a bien été sélectionné, on passe à la suite : 
//on créé un string qui va récupérer le titre du manga sélectionné
        String titre = modelFavoris.getElementAt(index);

//on créé un objet manga, il recevra le manga correspondant dans les favoris de l'utuilisateur connecté
        Manga m = utilisateur.chercherFavoriParTitre(titre);
//si un manga est trouvé correspondant au titre donné    
        if (m != null) {
//alors on appelle la methode permettant de retirer le manga ne favori pour un utilisateur connecté        
            utilisateur.retirerFavori(m);

            //on fait aussi la suppression dans le fchier txt des favoris
            GestionFavoris gf = new GestionFavoris();
            gf.retirerFavori(utilisateur, m);
        }

//enfin ,si les if n'ont pas chopé d'anomalies, alors on peut retirer le manga des favoris de l'utilisateur
//on retire l'élément de la liste à l'indice indiqué
        modelFavoris.removeElementAt(index); // côté interface (on modifie le Model)

//on affiche un message informant que le manga a biuen été retiré
        JOptionPane.showMessageDialog(this, "Retiré des favoris : " + titre);

    }//GEN-LAST:event_btnRetirerActionPerformed

    private void btnRetourFavorisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourFavorisActionPerformed
        // TODO add your handling code here:
        //on créé une nouvelle fenetre accueil, on la rend visibl et on cache la fentre actuelle
        FenetreAccueil fa = new FenetreAccueil(gestionUsers, catalogue, utilisateur);
        this.setVisible(false);
        fa.setVisible(true);
    }//GEN-LAST:event_btnRetourFavorisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterManuel;
    private javax.swing.JButton btnRetirer;
    private javax.swing.JButton btnRetourFavoris;
    private javax.swing.JButton btnVoirMangaFavoris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listFavoris;
    private javax.swing.JScrollPane scrollFavoris;
    // End of variables declaration//GEN-END:variables
}
