/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_java.UI;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import projet_java.model.Catalogue;
import projet_java.model.Manga;
import projet_java.model.Utilisateur;
import projet_java.service.GestionUtilisateurs;

/**
 *
 * @author nabil
 */
public class FenetreResultats extends javax.swing.JFrame {

    //final permet d'^tre sur que quand on arrive dans cet ecran, le catalogue ou l'utilisateur ne changeront pas
    //le private permet que les infos de l'utilisateur connecté ne changent pas, donc l'utilisateur connecté ne changera pas avant déconnexion par exempke
    private final GestionUtilisateurs gestionUsers; //c'est lo'bjet qui gère les utilisateurs
    private final Catalogue catalogue; //le catalogue des mangas
    private final Utilisateur utilisateur; // c'est l'utilisateur qui est connecté
    private final JFrame ecranRetour;
    private final ArrayList<Manga> resultatsAffiches;
    private final DefaultListModel<String> modelResultats = new DefaultListModel<>();

    /**
     * Creates new form FenetreResultats
     */
    public FenetreResultats(GestionUtilisateurs gu, Catalogue cat, Utilisateur u, ArrayList<Manga> resultats, JFrame retour) {
        initComponents();

        this.gestionUsers = gu;
        this.catalogue = cat;
        this.utilisateur = u;
        if (resultats != null) {
            this.resultatsAffiches = resultats;           // on réutilise la liste passée
        } else {
            this.resultatsAffiches = new ArrayList<Manga>(); // sinon on part sur une liste vide
        }

        this.ecranRetour = retour;

        //réglages de la fentre
        setTitle("Résultats");
        setSize(520, 360);
        setLocation(260, 200);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        //on lie la liste à son model, et on rempli le model
        listeResultats.setModel(modelResultats);

        //on fait une boucle for each parcourant la liste des resukltats
        for (Manga m : this.resultatsAffiches) {
            //si le titre est rcupéré
            if (m != null && m.getTitre() != null) {
                //on l'ajoute à notre lsite
                modelResultats.addElement(m.getTitre());
            } else {
                //sinon, on ajoute l'élément mais on met un message disant qu'on n'a pas trouvé le titre
                modelResultats.addElement("(sans titre)");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titrePageResultats = new javax.swing.JLabel();
        scrollResultats = new javax.swing.JScrollPane();
        listeResultats = new javax.swing.JList<>();
        btnVoirFicheResultats = new javax.swing.JButton();
        btnRetourResultats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titrePageResultats.setText("Résultats de la recommandation");

        listeResultats.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeResultats.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollResultats.setViewportView(listeResultats);

        btnVoirFicheResultats.setText("Voir la fiche");
        btnVoirFicheResultats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoirFicheResultatsActionPerformed(evt);
            }
        });

        btnRetourResultats.setText("Retour");
        btnRetourResultats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourResultatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(titrePageResultats)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoirFicheResultats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRetourResultats))
                    .addComponent(scrollResultats, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titrePageResultats)
                .addGap(18, 18, 18)
                .addComponent(scrollResultats, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoirFicheResultats)
                    .addComponent(btnRetourResultats))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoirFicheResultatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoirFicheResultatsActionPerformed
        // TODO add your handling code here:

        //on créé un int qui va indiquer l'index de 'lélément dans la liste, par défaut c'est à -1
        int index = listeResultats.getSelectedIndex();
        //si on a aucun élément de choisi, donc si on a un index qui vaut -1 car c'est celui par défaut
        if (index == -1) {
            //on affiche un message disant qu'il faut choisir un manga pour voir sa fiche
            JOptionPane.showMessageDialog(this, "Sélectionne un manga d’abord.");
            //et on arrete la methode, rien ne se passe
            return;
        }

        //si un mlanga est sélectionné, donc index sera différent de -1
        //le manga se voit affecté celui qui est renseigné à l'indice de la liste sélectionné
        Manga m = resultatsAffiches.get(index);

        ////si aucun manga n'est trouvé, on affiche un message'
        if (m == null) {
            JOptionPane.showMessageDialog(this, "Impossible de retrouver l’élément sélectionné.");
            return;
        }

        //on ouvre la fiche indiquant que cette page, donc this, deviendra l'ecran de retour sur le prochain, grace à l'argument this en dessous
        FenetreFicheManga ffm = new FenetreFicheManga(gestionUsers, catalogue, utilisateur, m, this);
        this.setVisible(false);
        ffm.setVisible(true);

    }//GEN-LAST:event_btnVoirFicheResultatsActionPerformed

    private void btnRetourResultatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourResultatsActionPerformed
        // TODO add your handling code here:

        //on revient à la fenêtre qui a ouvert la fiche
        if (ecranRetour != null) {
            this.setVisible(false);//on cache la fenetre actuelle
            ecranRetour.setVisible(true);  //on affiche la fenetre d'avant
        } else {
            // normalement on entrera pas dans ce if mais si jamais j'ai raté un bout de code, en failsafe ça revient à l'accueil
            FenetreAccueil fa = new FenetreAccueil(gestionUsers, catalogue, utilisateur);
            this.setVisible(false);
            fa.setVisible(true);
        }
    }//GEN-LAST:event_btnRetourResultatsActionPerformed

    //y avait un main ici, j'ai supprimé

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetourResultats;
    private javax.swing.JButton btnVoirFicheResultats;
    private javax.swing.JList<String> listeResultats;
    private javax.swing.JScrollPane scrollResultats;
    private javax.swing.JLabel titrePageResultats;
    // End of variables declaration//GEN-END:variables
}
